name: ProcessInsights
channels:
  - defaults
  - https://repo-conda.oxy.com/
dependencies:
  - python=3.7.4
  - ciphercommon=2.0.23
  - pyyaml>=5.1
  - numpy=1.16.5
  - plotly=4.1.1
  - pandas=0.25.1
  - Flask=1.1.1
  - pip=19.2.3
  - pip:
    - azure-servicebus==0.50.1
    - wfastcgi=3.0.0